version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app

# NOTE: to run tests, in separate terminal, run `docker-compose run web npm run test`
